name = "ABCDeGraphGenerator"
uuid = "4a2737bb-2d33-40f8-8e7a-be9298b780d1"
authors = ["Bogumił Kamiński, Paweł Prałat, François Théberge, Tomasz Olczak"]
version = "0.2.4"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"

[compat]
StatsBase = "0.32, 0.33"
julia = "1.6"
